Add image including .NET 7
swissgrc/docker-azure-pipelines-sonarscannermsbuild-7 pull request #1
Opened 2023-06-06 19:30 UTC by pascalberger

Add image including .NET 7

2023-06-07 08:21 UTC, Xzelsius requested changes

2023-06-07 08:21 UTC, Xzelsius commented on README.md
> +| unstable     | Latest unstable release (from `develop` branch) | swissgrc/azure-pipelines-openjdk:17.0.7.0 | 7.0.302  | 18.16.0 | 1:2.39.2-1~bpo11+1 | 3.3.0   | ![Docker Image Size (tag)](https://i
Do we remove the unstable tag once this PR is merged?

2023-06-07 11:23 UTC, pascalberger commented on README.md
> +| unstable     | Latest unstable release (from `develop` branch) | swissgrc/azure-pipelines-openjdk:17.0.7.0 | 7.0.302  | 18.16.0 | 1:2.39.2-1~bpo11+1 | 3.3.0   | ![Docker Image Size (tag)](https://i
@Xzelsius I would keep `unstable` for pointing to the unstable release of the latest .NET version.

2023-06-07 15:01 UTC, Xzelsius commented on README.md
> +| unstable     | Latest unstable release (from `develop` branch) | swissgrc/azure-pipelines-openjdk:17.0.7.0 | 7.0.302  | 18.16.0 | 1:2.39.2-1~bpo11+1 | 3.3.0   | ![Docker Image Size (tag)](https://i
Means we would need to adjust the workflow that sets the tags. As you specifically set the unstable tag to another name, so there wont be a new unstable tag.

2023-06-08 07:33 UTC, pascalberger commented on README.md
> +| unstable     | Latest unstable release (from `develop` branch) | swissgrc/azure-pipelines-openjdk:17.0.7.0 | 7.0.302  | 18.16.0 | 1:2.39.2-1~bpo11+1 | 3.3.0   | ![Docker Image Size (tag)](https://i
Got it. Will remove the unstable tag from README and remove the tag after merging

2023-06-08 11:52 UTC, Xzelsius approved these changes

2023-06-08 11:53 UTC, Xzelsius requested changes

2023-06-08 11:53 UTC, Xzelsius commented on README.md
> +| 7-unstable   | Latest unstable release (from `develop` branch) | swissgrc/azure-pipelines-openjdk:17.0.7.0 | 7.0.302  | 18.16.0 | 1:2.39.2-1~bpo11+1 | 3.3.0   | ![Docker Image Size (tag)](https://i
6-unstable?

2023-06-09 11:02 UTC, Xzelsius approved these changes

2023-06-10 20:58 UTC, merged